### ISSUE TITLE
Error: Cannot find module 'node:url'

### ISSUE THREAD

**Issue by bajere** [3846masa/http-cookie-agent#212]
Hi,

I seem to be missing something. Do I need to install something extra? Running my code gives me;

```
Error: Cannot find module 'node:url'
Require stack:
- ...node_modules/http-cookie-agent/dist/http/create_cookie_agent.js
- ...node_modules/http-cookie-agent/dist/http/index.js
- ...node_modules/http-cookie-agent/http/index.js
- ...server/client.js
```

im importing your package via; `const { HttpCookieAgent, HttpsCookieAgent } = require('http-cookie-agent/http');` and using

```
...
this.instance = axios.create({
      baseURL: 'https://members-ng.iracing.com',
      httpAgent: new HttpCookieAgent({ cookies: { jar } }),
      httpsAgent: new HttpsCookieAgent({ cookies: { jar } }),
    })
...
```

I do not have any messages or errors in the IDE, it just fails on start.

Any pointers on what I'm doing wrong would be great.

Thanks in advance

**Comment by 3846masa** [comment]
Use Node.js >= v14.18.0 or >= v16.0.0 (except v15.x)

See https://nodejs.org/api/modules.html#core-modules
> v16.0.0, v14.18.0 | Added `node:` import support to `require(...)`.

**Comment by bajere** [comment]
Hi, I am using v16.15.1, so should be okay. i'll play around with nvm, maybe its a version issue

**Comment by bajere** [comment]
I had many node issue, all resolved now. thanks for the help, and package!

**Comment by moltar** [comment]
This still breaks with jest@26, even on supported Node versions

**Comment by moltar** [comment]
It was added here, recently: https://github.com/facebook/jest/pull/11331
