### ISSUE TITLE
axios 设置代理IP之后，cookies失效或设置错误

### ISSUE THREAD

**Issue by lengyue-ck** [3846masa/http-cookie-agent#238]
如果我不设置proxy 那么cookies一切正常，如果我这设置了proxy，cookies就设置错误了，对方网站提示我需要登陆

## Environments

- OS: [e.g. macOS]
- Node.js version: [e.g. 12.0.0]
- axios version: [e.g. 0.21.0]
- tough-cookie version: [e.g. 4.0.0]

**Comment by 3846masa** [comment]
Sharing code that reproduces the bug.

If the code is not shared, we will not be able to investigate and may close the issue.

**Comment by lengyue-ck** [comment]
import axios from "axios";
import {wrapper} from "axios-cookiejar-support";
import tough from "tough-cookie";

wrapper(axios);//包装axios
const jar = new tough.CookieJar();
jar.setCookieSync('a=1;', 'https://app.itihey.com/api/cookiesTest')
axios.get("https://app.itihey.com/api/cookiesTest", {
    jar
}).then(res => {
    console.log('没有设置代理IP的返回：' + res.data)
    //没有设置代理IP的返回：cookie----a=1
})
axios.get("https://app.itihey.com/api/cookiesTest", {
    jar,
    proxy:{
        host:'125.124.120.52',//这里的代理IP需要您自定配置一下
        port:5609

    }
}).then(res => {
    console.log('设置代理IP的返回：' + res.data)
    //设置代理IP的返回：cookie----null
})

**Comment by lengyue-ck** [comment]
我感觉应该是您代理IP proxy占用了 httpAgent导致无法提交Cookie，如果我增加一个这样的拦截器，在header上添加cookie就好了，但是我还是想知道这个问题

**Comment by 3846masa** [comment]
axios's proxy options cannot be used with `http-cookie-agent`.

Please try to use `http-cookie-agent` with `http-proxy-agent` library.

```js
import { createCookieAgent } from 'http-cookie-agent';
import httpProxyAgent from 'http-proxy-agent';
import httpsProxyAgent from 'https-proxy-agent';

const HttpProxyCookieAgent = createCookieAgent(httpProxyAgent.HttpProxyAgent);
const HttpsProxyCookieAgent = createCookieAgent(httpsProxyAgent.HttpsProxyAgent);

const jar = new CookieJar();

await axios.get('https://httpbin.org/cookies/set/session/userid', {
  httpAgent: new HttpProxyCookieAgent({ cookies: { jar }, host: '125.124.120.52' port: 5609 }),
  httpsAgent: new HttpsProxyCookieAgent({ cookies: { jar }, host: '125.124.120.52' port: 5609 }),
});

const cookies = await jar.getCookies('https://httpbin.org');
console.log(cookies);
```

And also see https://github.com/3846masa/http-cookie-agent/tree/main/examples for more details.

**Comment by lengyue-ck** [comment]
我的代理IP不固定，每个每次请求都会改变，这样必须在拦截器上重新设置httpAgent 重新new HttpProxyCookieAgent吗？

**Comment by lengyue-ck** [comment]
``` javascript
this.instance.interceptors.request.use(async config => {
            if (config.url.includes('multimedia/log') || config.url.includes('work/addStudentWorkNew')) {
                config.proxy = await rdsGetIPs('cx_')
                config.headers['Cookie'] = this.cookies.getCookiesSync(config.url).map(item => {
                    return (item.key + '=' + item.value)
                }).join('; ')
            }
            return config
        })
```

这是我的拦截器，所有的请求，如果url包含xxx，那么就设置代理IP，如果使用您的方法，我必须在这里重新new HttpProxyCookieAgent吗？

**Comment by lengyue-ck** [comment]
如果我按您的设置之后，会报错Client network socket disconnected before secure TLS connection was established

**Comment by 3846masa** [comment]
> 这是我的拦截器，所有的请求，如果url包含xxx，那么就设置代理IP，如果使用您的方法，我必须在这里重新new HttpProxyCookieAgent吗？

Yes, You should set `config.httpAgent` / `config.httpsAgent` in interceptors when you want to change proxy by url.
However, this use case is not expected and may not work well.

We do not plan to support any use case that is not a common use case. Sorry.
