### ISSUE TITLE
Cannot find module 'deasync'

### ISSUE THREAD

**Issue by kuizuo** [3846masa/http-cookie-agent#291]
When i using with an asynchronous Cookie store(e.g. redis-cookie-store)，the following error message occurs

```
Error: you should install deasync library when cookies.async_UNSTABLE is true.
```

I'm sure I set `async_UNSTABLE` option to ture, just like the [sample code](https://github.com/3846masa/http-cookie-agent#using-with-an-asynchronous-cookie-store).

I found Cannot find module `deasync` through debugging, below is my screenshot of debug page

![image](https://user-images.githubusercontent.com/61005888/197122140-dc143246-7cfb-4956-b435-350c753d158d.png)

Moreover I also found that `deasync` is not in node_modules.

![image](https://user-images.githubusercontent.com/61005888/197122695-bd103cf0-5bfe-424c-a44f-220718b6595d.png)

Move `deasync` dependencies to dependencies, Does this resolve the bug?

![image](https://user-images.githubusercontent.com/61005888/197122838-e3633f5d-2156-4d46-b5ec-7f1a0169a064.png)

**Comment by 3846masa** [comment]
deasync is not required in most cases.
Therefore, deasync is peer depenencies, and if you need deasync, you should install it yourself.
