### ISSUE TITLE
How to use proxy agent or an agent that requires parameter

### ISSUE THREAD

**Issue by damianobarbati** [3846masa/http-cookie-agent#399]
## Describe the bug

How are you supposed to pass options to the agent? 🤔

```js
import axios from 'axios';
import { CookieJar } from 'tough-cookie';
import axiosCurl from 'axios-curlirize';
import { createCookieAgent } from 'http-cookie-agent/http';
import createHttpProxyAgent from 'http-proxy-agent';

// where can I provide the following?
const proxy = 'http://49.0.2.242:8090';

// @ts-ignore
const Agent = createCookieAgent(createHttpProxyAgent);
const jar = new CookieJar();
const agent = new Agent({ cookies: { jar } });

const httpAgent = agent;
const httpsAgent = agent;

const axios_instance = axios.create({
  timeout: 10000,
  // @ts-ignore
  jar,
  httpAgent,
  httpsAgent,
});
```

**Comment by 3846masa** [comment]
See this example.
https://github.com/3846masa/http-cookie-agent/blob/v5.0.2/examples/http-proxy-agent/basic.mjs

**Comment by damianobarbati** [comment]
@3846masa thanks I managed to have this working, but how do I pass credentials for authenticated proxies?

**Comment by dstampher** [comment]
> See this example. https://github.com/3846masa/http-cookie-agent/blob/v5.0.2/examples/http-proxy-agent/basic.mjs

This didn't work for me, using https-proxy-agent.  If I only pass in host and port as you showed in that example, there are 7 other missing properties.
