### ISSUE TITLE
How do I use this library with https-proxy-agent?

### ISSUE THREAD

**Issue by dstampher** [3846masa/http-cookie-agent#511]
```
let proxyUri = `${account.proxy.protocol}://${account.proxy.host}:${account.proxy.port}`;
  let Agent = createCookieAgent(HttpsProxyAgent)
  let jar = new CookieJar();
  if (account.cookies) {
    for (let cookie of account.cookies) {
      jar.setCookie(`${cookie.name}=${cookie.value}; Domain=${cookie.domain}; Path=${cookie.path}; ${cookie.secure ? 'Secure' : ''}; ${cookie.httpOnly ? 'HttpOnly' : ''}`, 'https://' + cookie.domain, (err, cookie) => {});
    }
    const cookieAgent = new Agent(proxyUri, { cookies: { jar } });
```

I need to pass in the proxyUri but I get an error

Argument of type '{ cookies: { jar: CookieJar; }; }' is not assignable to parameter of type 'HttpsProxyAgentOptions<string> | undefined'.
  Object literal may only specify known properties, and 'cookies' does not exist in type 'HttpsProxyAgentOptions<string>'.ts(2345)
(property) cookies: {
    jar: CookieJar;
}

Please update the docs to show an example where an agent that is being wrapped can pass values in...

**Comment by dstampher** [comment]
I can confirm after further research that the API of this library is quite odd, and that instantiating an extended version of https-proxy-agent is a nightmare because of the lack of docs.  https-proxy-agent is an extremely popular library, and so without a good example it creates frustration...

```
import { createCookieAgent } from "http-cookie-agent/http";
import { HttpsProxyAgent } from "https-proxy-agent";
import {CookieJar} from "tough-cookie";
import axios from "axios";
let HttpsProxyCookieAgent = createCookieAgent(HttpsProxyAgent);
let cookieJar = new CookieJar();
cookieJar.setCookieSync("name=david", "http://ip-api.com");
let httpsProxyCookieAgent = new HttpsProxyCookieAgent("http://localhost:8080", {cookies: {jar: cookieJar}}}); //Nothing works.  I can't create this object, there will always be an error.  I tried many different ways.
axios.get("http://ip-api.com/json", {
  httpsAgent: httpsProxyCookieAgent,
  httpAgent: httpsProxyCookieAgent,
});
```

**Comment by dstampher** [comment]
After further testing I can also confirm that the example provided in this repo regarding http-proxy-agent does not work at all.

First typescript gives an error saying that port should be a string.  So I write it in quotes, and receive a similar error to the https-proxy-agent library.

Argument of type '{ cookies: { jar: CookieJar; }; host: string; port: string; }' is not assignable to parameter of type '(string | URL) & CookieAgentOptions'.
  Type '{ cookies: { jar: CookieJar; }; host: string; port: string; }' is not assignable to type 'URL & CookieAgentOptions'.
    Type '{ cookies: { jar: CookieJar; }; host: string; port: string; }' is missing the following properties from type 'URL': hash, hostname, href, origin, and 7 more.ts(2345)

**Comment by dstampher** [comment]
Is this repo no longer maintained???  The lack of response has completely stalled my project.

I might stop using Typescript since there is no alterative library.

**Comment by dstampher** [comment]
I am still trying to figure this out, if someone can help.

import { HttpsProxyAgent } from "https-proxy-agent";
import { Cookie, CookieJar } from "tough-cookie";
import { createCookieAgent } from "http-cookie-agent/http";
import axios from "axios";

let CookieAgent = createCookieAgent(HttpsProxyAgent);
let jar = new CookieJar();
let cookieAgent = new CookieAgent({
  cookies: {
    jar: jar,
  },
  host: "localhost",
  hash: "test",
  port: "8080",
  username: "test",
  password: "test",
  protocol: "http:",
  hostname: "test",
  href: "test",
  origin: "test",
  pathname: "test",
  search: "test",
  searchParams: new URLSearchParams("test"),
  toJSON: () => "test",
});


This makes the typescript errors go away, but I just used junk test property values.  There must be a better way.

**Comment by dstampher** [comment]
After speaking with GPT-4, it has been confirmed that this is a bug.  

"It seems like createCookieAgent expects a type that is both a string | URL and CookieAgentOptions. These are inherently incompatible as string and URL are primitive types and cannot contain properties, unlike CookieAgentOptions.

This situation arises from a misunderstanding of the createCookieAgent function's API. I'm afraid it's impossible to create an object that is both a string or URL and an instance of CookieAgentOptions, as they're fundamentally different types of objects."

Because https-proxy-agent is so widely used (~30 million monthly installs), the fact that http-cookie-agent does not allow you to extend this agent greatly reduces the usability of http-cookie-agent.

As it seems that this repo is abandoned, I ask for any alternative libraries which provide similar functionality.  It seems we will need a new repo.

**Comment by dstampher** [comment]
Closing this now as I have implemented this functionality myself.

**Comment by 3846masa** [comment]
With the release of https-proxy-agent v6 last month (2023/05/05), type definitions were not working properly.

This has been supported in http-cookie-agent v5.0.4.
