### ISSUE TITLE
Doesn't work with bun, no cookies emitted or captured

### ISSUE THREAD

**Issue by Thinkscape** [3846masa/http-cookie-agent#692]
## Describe the bug

When run with bun as runtime, doesn't seem to include nor parse cookies.
Tested with global `fetch` and `axios`.

## To Reproduce

1. Run the examples from this repo or https://github.com/3846masa/axios-cookiejar-support
2. Send a request which responds with `set-cookie` headers.
3. Send another request

## Expected behavior

The cookie jar has cookies. The second request sends them back

## Actual behaviour

Cookie jar is empty.
Second request has no `cookie` header.

Setting cookies manually with `jar.setCookieSync(...)` between requests, then sending second request still results in second request not containing `cookie` header 🤔 

## Repro

```ts
const jar = new CookieJar(undefined, {
// -- Tried all of those, didn't help
//  looseMode: true,
//  prefixSecurity: "unsafe-disabled",
//  rejectPublicSuffixes: false,
//  allowSpecialUseDomain: true,
});
const client = wrapper(axios.create({jar }));

await client.get('https://some.site');
console.log(jar.toJSON());
```
```
bun run example.ts
```

## Environments

- OS: macos
- Bun version: 1.0.12
- axios version: 1.6.1
- tough-cookie version: 4.1.3

**Comment by Thinkscape** [comment]
Tried with got, but it's got other problems that prevent it from running. Given that bun has its own `fetch` implementation, that might be what's causing trouble. See https://github.com/oven-sh/bun/pull/4395

**Comment by 3846masa** [comment]
Thank you for reporting the issue.

The http-cookie-agent relies on undici, the internal implementation of fetch in Node.js.
Therefore, it will not work with any fetch implementation other than Node.js.

I would like to make it work with fetch implementations other than Node.js in the future, but there is no plan yet.
