### ISSUE TITLE
Document how to use `http-cookie-agent` with `http-proxy-agent`

### ISSUE THREAD

**Issue by skilbjo** [3846masa/http-cookie-agent#770]
Hi, I see differences in documentation in `axios-cookiejar-support` and `http-cookie-agent` on how to use a proxy so want you to provide clarification.

docs in `axios-cookiejar-support`: https://github.com/3846masa/axios-cookiejar-support/blob/12be1d2725cff1f46c07bf0510941baffaaef5b4/MIGRATION.md?plain=1#L108

```
const client = axios.create({
  httpsAgent: new HttpsProxyCookieAgent({ jar, hostname: '127.0.0.1', port: 8080 }),
});
```

example in `http-cookie-agent`: https://github.com/3846masa/http-cookie-agent/blob/e9a338dbacc9100d5dd6fdcadeb688cd9ed0f4ae/examples/http-proxy-agent/basic.mjs#L15

```
const agent = new HttpProxyCookieAgent('http://127.0.0.1:9000', { cookies: { jar } });
```

As you can see, the function signatures are different.

- is the way to pass in the jar, `{ jar }` or `{ cookies: { jar } }`
- is the first argument the option properties, or the uri of the proxy

?

**Comment by skilbjo** [comment]
the answer (after testing) is

```
  {
    cookies: { jar },
  }
```

the code in [http-cookie-agent/examples/http-proxy-agent/basic.mjs](https://github.com/3846masa/http-cookie-agent/blob/e9a338dbacc9100d5dd6fdcadeb688cd9ed0f4ae/examples/http-proxy-agent/basic.mjs#L15) is correct, 
and the code in https://github.com/3846masa/axios-cookiejar-support/blob/12be1d2725cff1f46c07bf0510941baffaaef5b4/MIGRATION.md?plain=1#L108 is incorrect

**Comment by 3846masa** [comment]
MIGRATION.md in axios-cookiejar-support was written 3 years ago.
Read the latest documentation.

The instructions for using http-cookie-agent with another Agent library are in README.md.
https://github.com/3846masa/http-cookie-agent#using-with-another-agent-library

Also, the Usage in README.md mentions `See also examples for more details.` 
https://github.com/3846masa/http-cookie-agent#usage
