### ISSUE TITLE
Process hangs when using async_UNSTABLE with an async cookie store

### ISSUE THREAD

**Issue by kwerdna19** [3846masa/http-cookie-agent#831]
## Describe the bug

Hello, I know it is called async_**UNSTABLE** but it seems no matter what I try, I am unable to get an async cookie store to work properly. The process hangs indefinitely at the first promise encountered.

I think it is an issue with`deasync` - which from my testing seems to be pretty broken when combined with `async/await`/promises in general.

Feel free to close the issue if you think it is more of a Node issue, but any help / ideas / working examples I can look at are appreciated.

## To Reproduce

reproduction repo: https://github.com/kwerdna19/http-cookie-repro

```
git clone https://github.com/kwerdna19/http-cookie-repro
cd http-cookie-repro
npm install
npm run start
```

## Expected behavior

Process should terminate and print number of cookies.

## Code that reproduces the bug

It seems to be a problem with deasync internally :(

## Environments

- OS: macOS m1
- Node.js version: I've tried 16, 18, and 20

```
		"deasync": "^0.1.29",
		"http-cookie-agent": "^6.0.1",
		"tough-cookie": "^4.1.3",
		"undici": "^6.10.2"
```

**Comment by 3846masa** [comment]
Sorry for the late communication.

From my research, I found that deasync often hangups when used with Promise.
* related: https://github.com/abbr/deasync/issues/140

Therefore, it is very difficult to handle the async cookie store using the current implementation of http-cookie-agent.

In the next version, async_UNSTABLE will be removed and support for the async cookie store will be completely removed.

Thanks for your understanding.
