### ISSUE TITLE
Verion 6.0.2 - Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by Tagliari** [3846masa/http-cookie-agent#842]
## Describe the bug

We have a bunch of applications with dependencies with "http-cookie-agent", and today we got several problems and difficulty identifying the reason.

I saw that you have a new version "http-cookie-agent": "6.0.2" and we rollback to 6.0.1 and now, everything works well.

Please check what happened below:

app[web.1]: > node dist/server.js
app[web.1]: 
app[web.1]: /node_modules/http-cookie-agent/dist/utils/create_cookie_header_value.js:9
app[web.1]: const _require = 'require' in globalThis ? globalThis.require : (0, _nodeModule.createRequire)(import.meta.url);
app[web.1]:                                                                                                       ^^^^
app[web.1]: 
app[web.1]: SyntaxError: Cannot use 'import.meta' outside a module
app[web.1]:     at internalCompileFunction (node:internal/vm:128:18)
app[web.1]:     at wrapSafe (node:internal/modules/cjs/loader:1279:20)
app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1331:27)
app[web.1]:     at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
app[web.1]:     at Module.load (node:internal/modules/cjs/loader:1205:32)
app[web.1]:     at Module._load (node:internal/modules/cjs/loader:1021:12)
app[web.1]:     at Module.require (node:internal/modules/cjs/loader:1230:19)
app[web.1]:     at require (node:internal/modules/helpers:179:18)
app[web.1]:     at Object.<anonymous> (/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js:8:35)
app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1368:14)
app[web.1]: 
app[web.1]: Node.js v21.7.1

**Comment by 3846masa** [comment]
Thanks for reporting. Issue was fixed by v6.0.3.
